# from galaxy
#- src: datadog.datadog
#  name: datadog.datadog
- src: grog.user
  name: grog.user
# https://galaxy.ansible.com/geerlingguy/security
- src: geerlingguy.security
  name: geerlingguy.security
# https://galaxy.ansible.com/geerlingguy/nginx
- src: geerlingguy.nginx
  name: geerlingguy.nginx
# https://galaxy.ansible.com/geerlingguy/certbot
- src: stackhpc.libvirt-host
  name: stackhpc.libvirt-host
- src: stackhpc.libvirt-vm
  name: stackhpc.libvirt-vm
- src: bertvv.dhcp
  name: bertvv.dhcp