---
- name: Import default official Zabbix GPG key.
  apt_key:
    url: "{{ zabbix_release_key }}"
    state: present
    
- name: Install default official Zabbix Release Repo
  tags: zabbix-agent
  apt:
    deb: "{{ zabbix_release_url }}"
    state: present

- name: Install the latest version of Zabbix Agent from official release repo
  tags: zabbix-agent
  apt:
    name: zabbix-agent
    state: present
...