---

- name: oc login with admin
  command: "oc login {{ public_master_url }} --username {{ username }} --password {{ password }} --insecure-skip-tls-verify=true"

- name: select project default
  command: "oc project default"

- command: oc delete all --selector='router'
  ignore_errors: true

- command: oc delete serviceaccount router
  ignore_errors: true

- command: oc delete clusterrolebindings router-router-role
  ignore_errors: true

- name: add policy privileged to system:serviceaccount:default:router
  command: oadm policy add-scc-to-user privileged system:serviceaccount:default:router

- name: add policy hostnetwork to router
  command: oadm policy add-scc-to-user hostnetwork -z router

- name: deploy router
  command: oadm router --service-account=router --expose-metrics --selector='router-node=true' --images='openshift/origin-${component}:v1.2.0'