---

- name: Adjust locale for CentOS - {{ locale }}
  command: localectl set-locale LANG={{ locale }}
  when: ansible_distribution == 'CentOS'

- name: Adjust locale for RedHat - {{ locale }}
  when: ansible_distribution == 'RedHat'
  replace: dest=/etc/sysconfig/i18n regexp='(LANG.*\nSYSFONT.*"$)' replace='LANG="{{ locale }}"\nSYSFONT="latarcyrheb-sun16"'

- name: Change timezone to {{ timezone }}
  command: timedatectl set-timezone {{ timezone }}

#- name: Adjust timezones to {{ timezone }}
#  file: force=yes path=/etc/localtime src=/usr/share/zoneinfo/America/Sao_Paulo state=link
- name: Add Alias rm cp mv with -i in /etc/bashrc
  blockinfile:
    dest: /etc/bashrc
    state: present
    insertafter: "^# vim:ts=4:sw=4"
    block: |
      alias rm='rm -i'
      alias cp='cp -i'
      alias mv='mv -i'

- name: Add {{ user }} user "!requiretty" in /etc/sudoers
  lineinfile: dest=/etc/sudoers state=present insertafter="^Defaults    requiretty" line="Defaults:{{ user }} !requiretty" validate='visudo -cf %s'
  when: ansible_distribution == 'CentOS'
  
- include: epel.yml

- name: Disable EPEL for security purposes
  command: sed -i -e "s/^enabled=1/enabled=0/" /etc/yum.repos.d/epel.repo

- name: Installing essential packages
  yum: name={{ item }} state=present enablerepo=epel
  with_items: "{{ packages }}"

- name: Enable SELINUX=enforcing and SELINUXTYPE=targeted
  selinux: policy=targeted state=enforcing

- name: Enable SELinux persistent virt_use_nfs
  seboolean: name=virt_use_nfs state=yes persistent=yes

- name: Enable SELinux persistent virt_sandbox_use_nfs
  seboolean: name=virt_sandbox_use_nfs state=yes persistent=yes