---
server_instance: jboss6_name
instance_path: "/opt/{{ server_instance }}"
catalina_sh: "{{ instance_path }}/bin/catalina.sh"
run_conf: "{{ instance_path }}/bin/run.conf"
jrockit_path: /usr/java/jrockit-jdk1.6.0_45-R28.2.7-4.1.0
date: "{{ lookup('pipe', 'date +%H%M-%d%m%Y') }}"
jrockit_pkg: jrockit-jdk1.6.0_45-R28.2.7-4.1.0.tar.gz
...
