# Copyright 2014 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: "[RedHat] Install the Python bindings for SELinux, for Ansible."
  yum: name=libselinux-python state=present

- name: "[RedHat] Add the Stackdriver yum repository."
  get_url:
    url: "{{ stackdriver_package_repo }}"
    dest: /etc/yum.repos.d/stackdriver.repo

- name: "[RedHat] Install the Stackdriver agent."
  yum: name={{ stackdriver_collectd_package }} state=present
  notify: stackdriver updated

- name: "[RedHat] Install YAJL if needed for curl_json."
  yum: name=yajl state=present
  when: stackdriver_enabled_plugins|intersect(stackdriver_plugins_based_on_curl_json)
  notify:
    - restart collectd
    - stackdriver updated

- name: "[RedHat] Install hiredis library if needed for redis plugin."
  yum: name=hiredis enablerepo=epel state=present
  when: stackdriver_redis_enabled
  notify:
    - restart collectd
    - stackdriver updated
