---

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present

- name: Install latest EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  retries: 3
  delay: 10