---

- name: Adjust locale for CentOS - {{ locale }}
  command: localectl set-locale LANG={{ locale }}
  when: ansible_distribution == 'CentOS'

- name: Adjust locale for RedHat - {{ locale }}
  when: ansible_distribution == 'RedHat'
  replace: dest=/etc/sysconfig/i18n regexp='(LANG.*\nSYSFONT.*"$)' replace='LANG="{{ locale }}"\nSYSFONT="latarcyrheb-sun16"'

- name: Adjust timezones to {{ timezone }}
  file: force=yes path=/etc/localtime src="/usr/share/zoneinfo/{{ timezone }}" state=link