---

- include: locale_timezone.yml

- name: "Add Alias rm cp mv with -i in /etc/bashrc"
  blockinfile:
    dest: /etc/bashrc
    state: present
    insertafter: "^# vim:ts=4:sw=4"
    block: |
      alias rm='rm -i'
      alias cp='cp -i'
      alias mv='mv -i'

- include: epel-repo.yml

- name: "Disable EPEL repo for security purposes"
  replace: dest=/etc/yum.repos.d/epel.repo regexp='^(enabled=1)$' replace='enabled=0' backup=yes

- name: "Installing essential packages"
  yum: name={{ item }} state=present enablerepo=epel update_cache=yes
  with_items: "{{ packages }}"

- name: "Disable Extras repo for security purposes"
  command: "yum-config-manager --disable extras"

- include: selinux.yml