---

- name: Setup facts
  setup:
    gather_subset:
      - 'network'

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- include_tasks: timezone.yml

- name: "Add Alias rm cp mv with -i in {{ bashrc_file }}"
  tags: common
  blockinfile:
    dest: "{{ bashrc_file }}"
    state: present
    insertafter: "^# vim:ts=4:sw=4"
    block: |
      alias rm='rm -i'
      alias cp='cp -i'
      alias mv='mv -i'
      alias ll='ls -ahlF --color=auto'

- include_tasks: redhat-custom.yml
  when: ansible_facts['os_family'] == "RedHat"

- include_tasks: debian-custom.yml
  when: ansible_facts['os_family'] == "Debian"

- include_tasks: network.yml
  when: fresh_install is defined

# - include_tasks: ntpconf.yml

- include_tasks: ssh_pub.yml

...