---

#- include: satellite-bootstrap.yml
#  when: cloud_account is not defined and ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version']|int > 6

- name: Register system and add subscription
  redhat_subscription:
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"
    state: present
    auto_attach: yes
  when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version']|int > 6

- import_tasks: epel-repo.yml

- name: "Installing mandadory packages"
  tags: common
  yum: 
    name: "ca-certificates"
    state: latest
    update_cache: yes
    disablerepo: "epel"

- name: "Installing essential packages"
  tags: common
  yum: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
    enablerepo: "{{ subscription_enablerepo }}"

- name: "Installing essential packages distrib version < 8"
  tags: common
  yum: 
    name:
      - NetworkManager-glib
      - libsemanage-python
      - policycoreutils-python
      - yum-plugin-security
    state: present
    update_cache: yes
    enablerepo: "{{ subscription_enablerepo }}"
  when: ansible_facts['distribution_major_version']|int < 8

- name: "Installing essential packages distrib version = 8"
  tags: common
  yum: 
    name:
      - NetworkManager-libnm
      - policycoreutils-python-utils
    state: present
    update_cache: yes
    enablerepo: "{{ subscription_enablerepo }}"
  when: ansible_facts['distribution_major_version']|int == 8

- name: "Update tzdata to latest"
  tags: common
  yum: 
    name: "tzdata"
    state: latest
    update_cache: yes

- name: "Disable EPEL repo for security purposes"
  tags: common
  command: "yum-config-manager --disable epel"

- name: "Disable Extras repo for security purposes"
  tags: common
  command: "yum-config-manager --disable extras"
  when: ansible_facts['distribution_major_version']|int < 8

- name: "Clean orphan and unused packages from YUM"
  tags: common
  command: yum clean all
