---

- name: Enable SELINUX=enforcing and SELINUXTYPE=targeted
  selinux: policy=targeted state=enforcing

- name: Enable SELinux persistent virt_use_nfs
  seboolean: name=virt_use_nfs state=yes persistent=yes

- name: Enable SELinux persistent virt_sandbox_use_nfs
  seboolean: name=virt_sandbox_use_nfs state=yes persistent=yes