---
- name: "Adjust host timezone to {{ timezone }} symlink /etc/localtime"
  tags: common-timezone
  file:
    src: "/usr/share/zoneinfo/{{ timezone }}"
    force: yes
    path: /etc/localtime
    state: link
